### ISSUE TITLE
Question: Is this front-ended by leiningen?

### ISSUE THREAD

**Issue by pmonks** [slipset/deps-ancient#3]
i.e. do I type something like `lein deps-ancient` to invoke this tool?  Or is this a standalone tool, in which case how does it differ from [Depot](https://oli.me.uk/2018-03-29-finding-new-dependencies-with-depot/)?

While standalone tools are adequate, I'd prefer something that was more tightly integrated with my existing Leiningen workflow.

**Comment by slipset** [comment]
It's standalone and does not differ from Depot.
And I didn't know about Depot :)

**Comment by pmonks** [comment]
Yeah cool.  Having something like Depot / deps-ancient front-ended by Leiningen would be ideal.  Maybe deps-ancient can switch more to that model?
